workflows:
  catapp-workflow:
    name: Cat App Pipeline
    scripts:
      - name: Initialising CI/CD
        script: echo 'Starting CI/CD'
    publishing:
      email:
        recipients:
          - yfarahi@risinggalaxy.com
