workflows:
  catapp-workflow:
    name: Cat App Pipeline
    scripts:
	- name: CICD Initialised
        - script: "Let there be CI/CD"
    publishing:
      email:
	recipients:
	  - yfarahi@risinggalaxy.com

